### ISSUE TITLE
Support for SSL vhost verification

### ISSUE THREAD

**Issue by roweryan** [kuba/simp_le#27]
I don't know if letsencrypt supports this, but could simp_le allow the verification url (/.well-known/acme-challenge/STRING) to be hosted on an SSL server?

I have only one vhost running, it's using an existing SSL cert, and I want to replace it with letsencrypt.

At the present time I have to setup an additional vhost without SSL running on port 80 just to do the verification part. I don't think any security would be lost by allowing the verification to occur over SSL.

**Comment by kuba** [comment]
Unfortunately, this is not possible because ACME protocol requires [0] stuff to be hosted on port 80. However, ACME CA server will follow any HTTP redirects, so easiest way to overcome it is to create a catch-all vhosts that redirects all http:// to https://. There is not much `simp_le` can do here, I'm afraid.

[0] https://github.com/ietf-wg-acme/acme/blob/2fec3301a4390b707c8d118f173c16f8dfa25c4f/draft-ietf-acme-acme.md#http

**Comment by ThomasWaldmann** [comment]
oh, maybe this was the culprit for me also. site runs on https already. have to check the http redirects.

is there already a ticket open somewhere (where?) about this problem? maybe a service to propagate TLS usage shouldn't make life complicated for people who already use https (only).
