### ISSUE TITLE
Why check for EEXIST?

### ISSUE THREAD

**Issue by Lekensteyn** [kuba/simp_le#31]
While auditing this project I found a weird check in two places for `errno.EEXIST`:

``` py
class ExternalIOPlugin(OpenSSLIOPlugin):
    # ...

    def persisted(self):
        """Call the external script and see which data is persisted."""
        try:
            output = subprocess.check_output([self.script, 'persisted'])
        except OSError as error:
            if error.errno != errno.EEXIST:
                return self.EMPTY_DATA
            raise
        return self.Data(
            key=('key' in output),
            cert=('cert' in output),
            chain=('chain' in output),
        )
```

Why would you return empty when the script cannot be executed (`EPERM` - insufficient permissions, `ENOENT` - file does not exist) while you raise an error for `EEXIST` ("File exists")? Under what circumstances can this occur?

Another place where such a check exists is:

``` py
def _load_existing_data(ioplugins):
    """Load existing data from disk.

    Returns:
      `IOPlugin.Data` instance with all components set or
      `IOPlugin.EMPTY_DATA`.
    """
    components = tuple(IOPlugin.EMPTY_DATA._asdict())
    existing = IOPlugin.EMPTY_DATA
    for plugin_name in ioplugins:
        try:
            data = IOPlugin.registered[plugin_name].load()
        except IOError as error:
            if not error.errno != errno.EEXIST:
                raise
```

None of the `load()` functions seem to raise an `EEXIST`. Is this coming from the OpenSSL library?

Additionally, this logic "not X != y" is not pretty readable.

**Comment by kuba** [comment]
You are absolutely right, thanks for analysis.
1. `ExternalIOPlugin` should rethrow any errors encountered while executing the external script. At the point `persisted`/`load`/`save` are called it is expected that script exists and is executable, because user must have specified `-f external_pem.sh`. Ignoring any non-`EEXIST` does not make sense at all.
2. `IOError` in `_load_existing_data` can arise from `open` in `load` methods of `KeyFile`/`ChainFile`/`FullchainFile`/`CertFile`. It should, however:
   - force `EMPTY_DATA` in case of `ENOENT` (which means that plugin did not persist anything before - first run)
   - happen inside the plugin's `load` method instead of `_load_existing_data`, because e.g. such check doesn't makes sense for external plugin

I believe that the root cause of problems you noticed lies in poorly defined interface for `IOPlugin`. I have attempted to fix this and all discovered bugs in 1f44510b9a564087d92871696035f25d5462d070.
