### ISSUE TITLE
simp_le support cli.ini file like operation ?

### ISSUE THREAD

**Issue by centminmod** [kuba/simp_le#44]
I am looking at simp_le as an alternative to official letsencrypt clients webroot authentication for use on low memory VPS systems 128MB to 768MB based in light of https://github.com/letsencrypt/letsencrypt/issues/1081

Question is whether simpl_le supports a cli.ini type approach ? 

Or better yet does it direct support official letsencrypt clients cli.ini set parameters ? Or is it essentially via full command line ?

cheers

George

**Comment by Lekensteyn** [comment]
I think that such functionality is better implemented in a wrapper script around the `simple_le.py` interface. From the manifest:

(1)  `UNIX philosophy`: Do one thing and do it well!
(7)  No configuration files. CLI flags as the sole interface! Users
    should write their own wrapper scripts or use shell aliases if
    necessary.

Maybe such a screipt is something to put into a `contrib/` directory?

**Comment by kuba** [comment]
`simp_le` doesn't support CLI the same params from the official Let's Encrypt client, and it will never be. Everything is configured through command line. And yes, a wrapper script is probably the best way to go. However, I don't see a point of putting such script in `contrib/` (or `examples/`), because it's settings are highly "personal"...
