### ISSUE TITLE
Move tests in sepeate module

### ISSUE THREAD

**Issue by trunneml** [kuba/simp_le#75]
The code would be much easier to read and understand when the unit tests would be extracted in to a seperate python module or package.

**Comment by kuba** [comment]
While I do agree usually on that statement, I find value in having tests in the same file in this project, because there is a single module only. This is nice e.g. because we can build a single `simp_le` binary (using PyInstaller, check `pyi` directory - although I'm not sure if it works atm) and run `simp_le --test` to verify everything works correctly. Another argument is that, if it becomes to hard to read a single file, then simp_le went the wrong way and included too many unnecessary features. For that reasons, I'll allow myself to close this report as WONTFIX (at least now).
